# Generated by Django 4.2.26 on 2025-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_delete_car_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, help_text='Nombre del archivo en static/images (ej: latte.webp)', max_length=200, verbose_name='Archivo de Imagen'),
        ),
    ]
